# This is a basic workflow to help you get started with Actions

name: GatherReferences

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 6'
    # runs every Saturday at midnight

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    environment: ZoteroPull
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      
      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install pandoc      
          sudo apt-get install pandoc-citeproc
          
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
          
      - id: cache-pipenv
        uses: actions/cache@v2.1.7
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}-${{ hashFiles('**/Pipfile') }}
          
      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --dev --deploy

      # Run the python script to pull all references from Zotero with tag
      - name: Zotero pull
        env:
          ZOTERO_LIBRARY_ID: ${{ secrets.ZOTERO_LIBRARY_ID }}
          ZOTERO_API_KEY: ${{ secrets.ZOTERO_API_KEY }}
        run: |
          pipenv run python generate_references.py \
            -t "SAMPL-website" \
            --lib-id "$ZOTERO_LIBRARY_ID" \
            --lib-type "group" \
            --api-key "$ZOTERO_API_KEY" \
            --outfile "_history/02_allreferences.md" \
            --headerfile "_history/allreferences_header.md"

      - name: Check if there are changes to all references list
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11

      - name: If changes commit changes to 02_allreferences.md
        if: steps.changes.outputs.changed == 1
        run: |
          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          git config --global user.name ${{ github.actor }}
          git add _history/02_allreferences.md
          git commit -m "zotero_pull action: Update 02_allreferences.md List"

      - name: If changes Create PR with updated references file
        if: steps.changes.outputs.changed == 1
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Zotero Pull Workflow update all references list"
